# -*- coding: utf-8 -*-
"""using_llama_with_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhDRXOJ_IaDpOdSZEVTSpZrnnuQMK21X
"""

# !pip uninstall -y transformers accelerate peft bitsandbytes trl
# !pip install -q -U bitsandbytes accelerate peft transformers trl datasets
# !pip install faiss-cpu

"""
RAG-Enhanced Humor Generation System
Combines fine-tuned Llama 3 8B with retrieval-augmented generation
"""

import os
import json
import torch
import numpy as np
from typing import List, Dict, Tuple
from dataclasses import dataclass
import pickle
from tqdm import tqdm

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from sentence_transformers import SentenceTransformer
import faiss

import wandb
from huggingface_hub import notebook_login

# ============================================================================
# CONFIGURATION
# ============================================================================

@dataclass
class RAGConfig:
    """Configuration for RAG system"""

    # Model paths
    BASE_MODEL = "meta-llama/Meta-Llama-3-8B-Instruct"
    LORA_PATH = r"C:\Users\Anwender\humor-project\src\generation\llama3_humor-neu\llama3-humor-lora\checkpoint-2300"
  # fine-tuned LoRA weights

    # RAG database
    JOKES_DATASET = r"C:\Users\Anwender\humor-project\data\humor_RAG_data_20000_RAG.jsonl" # Original training data
    RAG_INDEX_PATH = "./rag_index"

    # Embedding model for retrieval
    EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"  # Fast and good
    # Alternative: "sentence-transformers/all-mpnet-base-v2"  # Better quality, slower

    # Retrieval settings
    TOP_K = 10  # Number of similar jokes to retrieve
    CANDIDATE_K = 50
    LAMBDA = 0.4
    SIMILARITY_THRESHOLD = 0.2  # Minimum similarity score

    # Generation settings
    MAX_NEW_TOKENS = 256
    TEMPERATURE = 0.85
    TOP_P = 0.9

    USE_WANDB = False

    # Device
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

config = RAGConfig()

# ============================================================================
# RAG DATABASE BUILDER
# ============================================================================

class HumorRAGDatabase:
    """
    Build and query a RAG database of joke patterns and examples
    """

    def __init__(self, config: RAGConfig):
        self.config = config
        self.embedding_model = None
        self.index = None
        self.jokes_data = []

        self.use_diversity = True
        self.lambda_param = config.LAMBDA

    def build_database(self, jokes_file: str):
        """Build the RAG database from training jokes"""

        print("🏗️  Building RAG Database...")

        # Load embedding model
        print(f"  Loading embedding model: {self.config.EMBEDDING_MODEL}")
        self.embedding_model = SentenceTransformer(self.config.EMBEDDING_MODEL)
        self.embedding_model.to(self.config.DEVICE)

        # Load jokes
        print(f"  Loading jokes from: {jokes_file}")
        self.jokes_data = self._load_jokes(jokes_file)
        print(f"  Loaded {len(self.jokes_data)} jokes")

        # Create embeddings
        print("  Creating embeddings...")
        embeddings = self._create_embeddings()

        # Build FAISS index
        print("  Building FAISS index...")
        self.index = self._build_faiss_index(embeddings)

        # Save database
        self._save_database()

        print(f"✓ RAG Database built with {len(self.jokes_data)} jokes\n")

    def _load_jokes(self, jokes_file: str) -> List[Dict]:
        """Load jokes from JSONL file"""
        jokes = []

        with open(jokes_file, 'r', encoding='utf-8') as f:
            for line in f:
                data = json.loads(line)
                joke_text = data['messages'][1]['content']  # Assistant's response
                word1 = data.get('word1', '')
                word2 = data.get('word2', '')

                jokes.append({
                    'joke': joke_text,
                    'word1': word1,
                    'word2': word2,
                    'constraint_text': f"{word1} {word2}",
                })

        return jokes

    def _create_embeddings(self) -> np.ndarray:
        """Create embeddings for all jokes"""

        # We'll embed both the joke and the constraint words for better retrieval
        texts_to_embed = []
        for joke_data in self.jokes_data:
            # Combine constraint words and joke for richer embeddings
            combined_text = f"{joke_data['constraint_text']}: {joke_data['joke']}"
            texts_to_embed.append(combined_text)

        # Create embeddings in batches
        embeddings = self.embedding_model.encode(
            texts_to_embed,
            batch_size=32,
            show_progress_bar=True,
            convert_to_numpy=True
        )

        return embeddings

    def _build_faiss_index(self, embeddings: np.ndarray):
        """Build FAISS index for fast similarity search"""

        dimension = embeddings.shape[1]

        # Use IndexFlatIP for inner product (cosine similarity after normalization)
        index = faiss.IndexFlatIP(dimension)

        # Normalize embeddings for cosine similarity
        faiss.normalize_L2(embeddings)

        # Add to index
        index.add(embeddings)

        return index

    def _save_database(self):
        """Save database to disk"""

        os.makedirs(self.config.RAG_INDEX_PATH, exist_ok=True)

        # Save FAISS index
        faiss.write_index(self.index, f"{self.config.RAG_INDEX_PATH}/faiss.index")

        # Save jokes data
        with open(f"{self.config.RAG_INDEX_PATH}/jokes_data.pkl", 'wb') as f:
            pickle.dump(self.jokes_data, f)

        print(f"  ✓ Database saved to {self.config.RAG_INDEX_PATH}")

    def load_database(self):
        """Load pre-built database from disk"""

        print("📂 Loading RAG Database...")

        # Load embedding model
        self.embedding_model = SentenceTransformer(self.config.EMBEDDING_MODEL)
        self.embedding_model.to(self.config.DEVICE)

        # Load FAISS index
        self.index = faiss.read_index(f"{self.config.RAG_INDEX_PATH}/faiss.index")

        # Load jokes data
        with open(f"{self.config.RAG_INDEX_PATH}/jokes_data.pkl", 'rb') as f:
            self.jokes_data = pickle.load(f)

        print(f"✓ Loaded database with {len(self.jokes_data)} jokes\n")

    # def retrieve(self, query: str, word1: str = None, word2: str = None, k: int = None) -> List[Dict]:
    #     """
    #     Retrieve similar jokes based on query

    #     Args:
    #         query: Search query (e.g., the word pair or a description)
    #         word1: First constraint word (optional, for better retrieval)
    #         word2: Second constraint word (optional)
    #         k: Number of results to return

    #     Returns:
    #         List of relevant jokes with similarity scores
    #     """

    #     if k is None:
    #         k = self.config.TOP_K

    #     # Construct query text
    #     if word1 and word2:
    #         query_text = f"{word1} {word2}: {query}"
    #     else:
    #         query_text = query

    #     # Create query embedding
    #     query_embedding = self.embedding_model.encode(
    #         [query_text],
    #         convert_to_numpy=True
    #     )

    #     # Normalize for cosine similarity
    #     faiss.normalize_L2(query_embedding)

    #     # Search
    #     scores, indices = self.index.search(query_embedding, k)

    #     # Gather results
    #     results = []
    #     for score, idx in zip(scores[0], indices[0]):
    #         if score >= self.config.SIMILARITY_THRESHOLD:
    #             joke_data = self.jokes_data[idx].copy()
    #             joke_data['similarity_score'] = float(score)
    #             results.append(joke_data)

    #     return results

    def retrieve(self, query: str, word1: str = None, word2: str = None, k: int = None):
        """Main retrieval method with optional diversity"""

        if k is None:
            k = self.config.TOP_K

        if self.use_diversity:
            # Use MMR for diversity
            return self.retrieve_with_diversity(
                query, word1, word2,
                k=k,
                candidate_k=k * 4,  # Get 4x candidates
                lambda_param=self.lambda_param
            )
        else:
            # Fall back to pure semantic search
            return self._semantic_search(query, word1, word2, k=k)

    def retrieve_with_diversity(
        self,
        query: str,
        word1: str = None,
        word2: str = None,
        k: int = 5,
        candidate_k: int = 20,
        lambda_param: float = 0.5
    ) -> List[Dict]:
        """
        Retrieve jokes using Maximal Marginal Relevance (MMR)

        Args:
            query: Search query
            word1, word2: Constraint words
            k: Number of diverse results to return (final output)
            candidate_k: Number of candidates to consider (larger pool)
            lambda_param: Balance between relevance (1.0) and diversity (0.0)
                        0.5 = equal weight to both

        Returns:
            List of k diverse, relevant jokes
        """

        # Step 1: Get candidates using semantic search
        candidates = self._semantic_search(query, word1, word2, k=candidate_k)

        if len(candidates) <= k:
            return candidates

        # Step 2: Diversify using MMR
        diverse_results = self._mmr_diversify(candidates, k, lambda_param)

        return diverse_results

    def _semantic_search(
        self,
        query: str,
        word1: str = None,
        word2: str = None,
        k: int = 20
    ) -> List[Dict]:
        """
        Pure semantic search - this is your current retrieve() method
        Gets top-k most similar jokes
        """

        # Construct query
        if word1 and word2:
            query_text = f"{word1} {word2}: {query}"
        else:
            query_text = query

        # Create query embedding
        query_embedding = self.embedding_model.encode(
            [query_text],
            convert_to_numpy=True
        )
        faiss.normalize_L2(query_embedding)

        # Search
        scores, indices = self.index.search(query_embedding, k)

        # Gather candidates
        candidates = []
        for score, idx in zip(scores[0], indices[0]):
            if score >= self.config.SIMILARITY_THRESHOLD:
                joke_data = self.jokes_data[idx].copy()
                joke_data['similarity_score'] = float(score)
                joke_data['idx'] = idx
                candidates.append(joke_data)

        return candidates

    def _mmr_diversify(
        self,
        candidates: List[Dict],
        k: int,
        lambda_param: float = 0.5
    ) -> List[Dict]:

        if len(candidates) <= k:
            return candidates

        # Get embeddings for all candidates
        candidate_texts = [c['joke'] for c in candidates]
        candidate_embeddings = self.embedding_model.encode(
            candidate_texts,
            convert_to_numpy=True,
            show_progress_bar=False
        )
        faiss.normalize_L2(candidate_embeddings)

        # Selected indices
        selected_indices = []
        selected_embeddings = []

        # Always start with the most relevant (highest similarity score)
        best_idx = 0  # First candidate is most similar to query
        selected_indices.append(best_idx)
        selected_embeddings.append(candidate_embeddings[best_idx])

        # Iteratively select k-1 more jokes
        for _ in range(k - 1):
            best_score = -np.inf
            best_candidate_idx = None

            # For each remaining candidate
            for idx, candidate in enumerate(candidates):
                if idx in selected_indices:
                    continue

                # Relevance: similarity to query (higher is better)
                relevance = candidate['similarity_score']

                # Diversity: dissimilarity to already selected (higher is better)
                # Calculate similarity to all selected jokes
                candidate_emb = candidate_embeddings[idx].reshape(1, -1)
                selected_emb_matrix = np.array(selected_embeddings)

                # Cosine similarity (dot product since normalized)
                similarities_to_selected = np.dot(selected_emb_matrix, candidate_emb.T).flatten()
                max_similarity_to_selected = np.max(similarities_to_selected)

                # MMR score
                mmr_score = (lambda_param * relevance -
                            (1 - lambda_param) * max_similarity_to_selected)

                if mmr_score > best_score:
                    best_score = mmr_score
                    best_candidate_idx = idx

            # Add best candidate
            if best_candidate_idx is not None:
                selected_indices.append(best_candidate_idx)
                selected_embeddings.append(candidate_embeddings[best_candidate_idx])

        # Return selected jokes in order of MMR selection
        return [candidates[idx] for idx in selected_indices]

# ============================================================================
# RAG-ENHANCED MODEL
# ============================================================================

class RAGHumorGenerator:
    """
    Combines fine-tuned Llama with RAG for enhanced humor generation
    """

    def __init__(self, config: RAGConfig):
        self.config = config
        self.model = None
        self.tokenizer = None
        self.rag_db = None

    def load_model(self):
        """Load fine-tuned model with LoRA"""

        print("🤖 Loading Fine-tuned Model...")

        # Load tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(
            self.config.LORA_PATH,
            trust_remote_code=True
        )

        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id

        print("  ✓ Tokenizer loaded")

        # Load base model (quantized for efficiency)
        from transformers import BitsAndBytesConfig

        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )

        base_model = AutoModelForCausalLM.from_pretrained(
            self.config.BASE_MODEL,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
        )

        print("  ✓ Base model loaded")

        # Load LoRA weights
        self.model = PeftModel.from_pretrained(base_model, self.config.LORA_PATH)
        self.model.eval()

        print("  ✓ LoRA weights loaded")
        print(f"  ✓ Model ready on {self.config.DEVICE}\n")

    def load_rag_database(self, build_if_missing: bool = True):
        """Load or build RAG database"""

        self.rag_db = HumorRAGDatabase(self.config)

        # Try to load existing database
        if os.path.exists(f"{self.config.RAG_INDEX_PATH}/faiss.index"):
            self.rag_db.load_database()
        elif build_if_missing:
            print("⚠️  RAG database not found, building new one...")
            self.rag_db.build_database(self.config.JOKES_DATASET)
        else:
            raise FileNotFoundError(f"RAG database not found at {self.config.RAG_INDEX_PATH}")

    def generate_with_rag(
        self,
        word1: str,
        word2: str,
        use_rag: bool = True,
        num_candidates: int = 1,
        return_retrieved: bool = False
    ) -> Dict:
        """
        Generate joke with optional RAG enhancement

        Args:
            word1: First constraint word
            word2: Second constraint word
            use_rag: Whether to use RAG (True) or just fine-tuned model (False)
            num_candidates: Number of jokes to generate
            return_retrieved: Whether to return retrieved examples

        Returns:
            Dictionary with generated joke(s) and metadata
        """

        retrieved_jokes = []

        # Step 1: Retrieve similar jokes if using RAG
        if use_rag and self.rag_db is not None:
            query = f"joke with {word1} and {word2}"
            retrieved_jokes = self.rag_db.retrieve(
                query=query,
                word1=word1,
                word2=word2,
                k=self.config.TOP_K
            )

        # Step 2: Construct prompt with retrieved context
        prompt = self._construct_prompt(word1, word2, retrieved_jokes)

        # Step 3: Generate
        generated_jokes = []
        for _ in range(num_candidates):
            joke = self._generate_joke(prompt)
            generated_jokes.append(joke)

        # Prepare result
        result = {
            'word1': word1,
            'word2': word2,
            'generated_jokes': generated_jokes,
            'best_joke': generated_jokes[0] if generated_jokes else "",
            'used_rag': use_rag,
            'num_retrieved': len(retrieved_jokes)
        }

        if return_retrieved:
            result['retrieved_examples'] = retrieved_jokes

        return result

    def _construct_prompt(self, word1: str, word2: str, retrieved_jokes: List[Dict]) -> str:
        """Construct prompt with optional RAG context"""

        base_instruction = f"Generate a funny joke that naturally includes both of these words: '{word1}' and '{word2}'. The joke should be creative, humorous, and incorporate both words seamlessly."

        if not retrieved_jokes:
            # No RAG - just base instruction
            return base_instruction

        # With RAG - add examples as inspiration
        context = """You are a comedian. You are generating humor.

A joke is funny because multiple cognitive mechanisms work together at once.
Do NOT copy wording, phrasing, or structure from the examples.
Instead, analyze WHY they work.

For each example below, humor may come from one or more of the following factors:
- Expectation violation (what the listener predicts vs what actually happens)
- Internal contradiction or incongruity
- Reversal of roles, status, or intent
- Literal interpretation of figurative language
- Treating something serious as trivial, or trivial as serious
- Absurd logic presented as reasonable
- Social norm violation that is harmless
- Overly confident reasoning applied to something wrong
- Sudden re-interpretation of earlier information
- Misdirection followed by a clean punchline
- Emotional contrast (calm setup → extreme or petty conclusion)
- Timing and brevity (a sharp, minimal punchline)

Below are jokes that successfully combine several of these mechanisms.
For each one, mentally identify:
- What expectation is created
- What assumption is broken
- What logical or social rule is violated
- Why the violation feels safe or playful rather than confusing

Examples:"""

        for i, joke_data in enumerate(retrieved_jokes[:3], 1):  # Use top 3
            context += f"Example {i}: {joke_data['joke']}\n"

        context += f"""\n- Create a NEW joke that naturally includes BOTH of these words: "{word1}" and "{word2}"
- The joke must use at least TWO humor mechanisms from the list above
- The punchline should reframe the setup in an unexpected but internally consistent way
- The humor should come from meaning, not wordplay alone
- Do NOT explain the joke
- Do NOT reference the examples
- DO NOT explain why is the joke funny.
- DO NOT elaborate on joke.

Generate only the joke text and nothing else., {base_instruction.lower()}"""

        return context

    def _generate_joke(self, prompt: str) -> str:
        """Generate a single joke"""

        # Format with chat template
        messages = [{"role": "user", "content": prompt}]
        formatted_prompt = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        # Tokenize
        inputs = self.tokenizer(formatted_prompt, return_tensors="pt").to(self.model.device)

        # Generate
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=self.config.MAX_NEW_TOKENS,
                temperature=self.config.TEMPERATURE,
                top_p=self.config.TOP_P,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                eos_token_id=self.tokenizer.eos_token_id,
            )

        # Decode
        generated = self.tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Extract assistant's response
        if "assistant" in generated:
            joke = generated.split("assistant")[-1].strip()
        else:
            joke = generated[len(formatted_prompt):].strip()

        return joke

    def batch_generate(
        self,
        word_pairs: List[Tuple[str, str]],
        use_rag: bool = True
    ) -> List[Dict]:
        """Generate jokes for multiple word pairs"""

        results = []

        print(f"🎭 Generating jokes for {len(word_pairs)} word pairs...")

        for word1, word2 in tqdm(word_pairs):
            result = self.generate_with_rag(word1, word2, use_rag=use_rag)
            results.append(result)

        return results

# ============================================================================
# EVALUATION & COMPARISON
# ============================================================================

class RAGEvaluator:
    """Compare RAG vs non-RAG generation"""

    @staticmethod
    def compare_generations(generator: RAGHumorGenerator, test_pairs: List[Tuple[str, str]]):
        """Compare RAG-enhanced vs vanilla fine-tuned model"""

        print("🔬 Comparing RAG vs Non-RAG Generation\n")
        print("="*80)

        for word1, word2 in test_pairs:
            print(f"\n📝 Words: {word1}, {word2}")
            print("-"*80)

            # Without RAG
            result_no_rag = generator.generate_with_rag(
                word1, word2,
                use_rag=False,
                return_retrieved=False
            )

            print(f"\n[Without RAG]")
            print(f"{result_no_rag['best_joke']}")

            # With RAG
            result_with_rag = generator.generate_with_rag(
                word1, word2,
                use_rag=True,
                return_retrieved=True
            )

            print(f"\n[With RAG] (Retrieved {result_with_rag['num_retrieved']} examples)")
            print(f"{result_with_rag['best_joke']}")

            if result_with_rag.get('retrieved_examples'):
                print(f"\n[Retrieved Examples:]")
                for i, ex in enumerate(result_with_rag['retrieved_examples'][:2], 1):
                    print(f"  {i}. {ex['joke'][:100]}... (score: {ex['similarity_score']:.3f})")

            print("="*80)

